# 1주차

In [ ]:
class Chatbot:
  def sayHello(self):
    print("say Hello")
  def sayMyName(self):
    print("My name is kbot :D")

chatbot=Chatbot()
chatbot.sayHello()
chatbot.sayMyName()

say Hello
My name is kbot :D


In [ ]:
class SimpleObj:
  def __init__(self):
    print("call__init__()")
  def __del__(self):
    print("call __del__()")
obj=SimpleObj()
print("obj instance is alive...")
del obj


call__init__()
obj instance is alive...
call __del__()


In [ ]:
class Calc:
  def __init__(self, init_value):
    self.value=init_value
  def add(self, n):
    return self.value+ n
  def sub(self, n):
    return self.value- n
  def mul(self, n):
    return self.value* n
  def div(self, n):
    return self.value/ n

cal= Calc(100)
print("value={0}".format(cal.value))

a= cal.add(100)
b= cal.sub(50)
c= cal.mul(2)
d= cal.div(2)
print("a= {0}, b= {1}, c= {2}, d= {3}". format(a, b, c, d))

value=100
a= 200, b= 50, c= 200, d= 50.0


In [ ]:
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

--2024-03-19 11:50:14--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz [following]
--2024-03-19 11:50:14--  https://www.dropbox.com/s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc562f85978bf7422cfbcb1061f7.dl.dropboxusercontent.com/cd/0/get/CPYXfaNM43tpqIZeSaegyUemrgeiN_fMtl1hKlFrKQ8kwiigRAxtj7lXQQ7mGb73xB3P9z-D9ccQfbWdEdTeduAti2brg9pbUwozMbpbzdBoyQtVhbRm8I-EdDuxHo3G5VZcajdqZYqNzzg8UoLeKCDA/file?dl=1# [following]
--2024-03-19 11:50:15--  https://uc562f85978bf7422cfbcb1061f7.dl.dropboxusercontent.com/cd/0/get/CPYXfaNM43tpqIZeSaegyUemrgeiN_fMtl1hKlFrKQ8kwiigRAxtj7l

### Kkma

In [ ]:
from konlpy.tag import Kkma

KKma=Kkma()
text= "아버지가 방에 들어갑니다."

morphs= KKma.morphs(text)
print(morphs)

pos= KKma.pos(text)
print(pos)

nouns= KKma.nouns(text)
print(nouns)

sentences= "오늘 날씨는 어때요? 내일은 덥다던데. "
s= KKma.sentences(sentences)
print(s)

['아버지', '가', '방', '에', '들어가', 'ㅂ니다', '.']
[('아버지', 'NNG'), ('가', 'JKS'), ('방', 'NNG'), ('에', 'JKM'), ('들어가', 'VV'), ('ㅂ니다', 'EFN'), ('.', 'SF')]
['아버지', '방']
['오늘 날씨는 어 때요?', '내일은 덥다 던데.']


### Komoran

In [ ]:
from konlpy.tag import Komoran

komoran= Komoran()
text= "아버지가 방에 들어갑니다."

morphs= komoran.morphs(text)
print(morphs)

pos=komoran.pos(text)
print(pos)

nouns= komoran.nouns(text)
print(nouns)

['아버지', '가', '방', '에', '들어가', 'ㅂ니다', '.']
[('아버지', 'NNG'), ('가', 'JKS'), ('방', 'NNG'), ('에', 'JKB'), ('들어가', 'VV'), ('ㅂ니다', 'EF'), ('.', 'SF')]
['아버지', '방']


### Okt

In [ ]:
from konlpy.tag import Okt

okt= Okt()
text= "이버지가 방에 들어갑니다."

morphs= okt.morphs(text)
print(morphs)

pos= okt.pos(text)
print(pos)

nouns= okt.nouns(text)
print(nouns)

text= "오늘 날씨가 좋아욬ㅋㅋ"
print(okt.normalize(text))

print(okt.phrases(text))

['이버지', '가', '방', '에', '들어갑니다', '.']
[('이버지', 'Noun'), ('가', 'Josa'), ('방', 'Noun'), ('에', 'Josa'), ('들어갑니다', 'Verb'), ('.', 'Punctuation')]
['이버지', '방']
오늘 날씨가 좋아요ㅋㅋ
['오늘', '오늘 날씨', '좋아욬', '날씨']


### 신조어인 경우

In [ ]:
#메모장에 신조어를 저장 후 파일을 연결하여 신조어를 인식할 수 있도록 한다.
#메모장 연결을 안한 경우 => 엔엘피를 한 단어로 안 보고 있음.

from konlpy.tag import Komoran

komoran= Komoran()
text= "우리 챗봇은 엔엘피를 좋아해."

pos= komoran.pos(text)
print(pos)

[('우리', 'NP'), ('챗봇은', 'NA'), ('엔', 'NNB'), ('엘', 'NNP'), ('피', 'NNG'), ('를', 'JKO'), ('좋아하', 'VV'), ('아', 'EF'), ('.', 'SF')]


In [ ]:
#메모장을 연결한 경우 => 엔엘피를 한 단어로 인식한다.

from konlpy.tag import Komoran

komoran= Komoran(userdic='./user_dic.tsv')
text= "우리 챗봇은 엔엘피를 좋아해."

pos= komoran.pos(text)
print(pos)

[('우리', 'NP'), ('챗봇은', 'NA'), ('엔엘피', 'NNG'), ('를', 'JKO'), ('좋아하', 'VV'), ('아', 'EF'), ('.', 'SF')]


# 2주차

In [2]:
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

--2024-03-21 11:39:09--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz [following]
--2024-03-21 11:39:10--  https://www.dropbox.com/s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9e2f1ab49a1ce46324c2c5be20.dl.dropboxusercontent.com/cd/0/get/CPhaE9CciDzPnu3N8OhsJBpBdT7bF0ljHHnE8-2ilnTXWYoR4ilMx35pz2gBU3FXqmTSI2tTMQC5i7KNWzbTkdVF4Ty6eHu8_XjNAAEEiHmZGr86vl97ackoegLKuHYRRh3CBO3PnroS7JUTybJy4HOx/file?dl=1# [following]
--2024-03-21 11:39:10--  https://uc9e2f1ab49a1ce46324c2c5be20.dl.dropboxusercontent.com/cd/0/get/CPhaE9CciDzPnu3N8OhsJBpBdT7bF0ljHHnE8-2ilnTXWYoR4ilMx35

### 원핫 인코딩 : 텍스트나 범주형 변수를 수치형 변수로 변환할 수 있다.  

단점: 불필요한 저장 공간 차지, 단어의 의미를 저장할 수 없음, 유사한 단어의 유사성을 모름  

해결방안: 임베딩  

단어를 벡터로 나타낼 수 있다.

In [5]:
from konlpy.tag import Komoran
import numpy as np

komoran= Komoran()
text= "오늘 날씨는 구름이 많아요"

nouns= komoran.nouns(text)
print(nouns)
dics={}

for word in nouns:
  if word not in dics.keys():
    dics[word]= len(dics)  #딕셔너리에 새로운 단어를 추가하기 전에 해당 딕셔너리의 키의 개수를 반환하는 것.
    #간단하게 생각하면 key와 value를 연관지어서 생각하면 될 거 같다.
print(dics)

#원-핫 인코딩 진행
nc= len(dics) #원-핫 인코딩을 진행할 단어의 개수
print(nc)
target= list(dics.values()) #각 단어의 고유한 인덱스를 리스트로 변환.
onehot= np.eye(nc)[target]
#원-핫 인코딩 진행
#np.eye() : 단위 행렬을 생성하는 함수.
#즉, nc × nc 크기의 단위 행렬을 만들고, 단위 행렬에서 target에 저장된 인덱스에 해당하는 행만 선택한다.

print(onehot)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###  Word2Vec 모델 학습

In [3]:
from gensim.models import Word2Vec
from konlpy.tag import Komoran
import time

def read_review_data(filename):
  with open(filename, 'r') as f:
    data= [line.split('\t') for line in f.read().splitlines()]
    #파일의 내용을 라인별로 읽어와 분리하여 line에 순서대로 저장-> line에 저장된 한줄을 tab으로 분리한다.
    data= data[1:] #첫 번째 라인인  헤더를 제외한 데이터를 반환.
  return data

start= time.time() #작업 시간으로 기록할 때 사용

print("1) 말뭉치 데이터 읽기 시작!")
review_data= read_review_data("./ratings.txt") #read_review_data(filename) 함수를 사용한 데이터 정리
#리뷰 데이터 개수
print("리뷰 데이터 개수", len(review_data))
#time.time()-start=> 현재 시간- 시작한 시간 = 특정 작업이 시작한 후 결과한 시간을 초단위로 나타낸 값
print("1) 말뭉치 데이터 읽기 완료: ", time.time()-start)
print("-"*30)

#명사만 추출
print("2) 형태소에서 명사만 추출 시작")
komoran=Komoran()
#sentence[1] : ratings.txt에는 1열에 리뷰에 관한 데이터가 들어있음.
docs= [komoran.nouns(sentence[1]) for sentence in review_data]
print("2) 형태소에서 명사만 추출 완료 ", time.time()-start)
print("-"*30)

#일반적으로 모델을 학습할 때 명사만 추출하여 학습시키는 것이 일반적이다.
#텍스트 데이터에 대한 전처리 과정 중 명사만 추출하는 게 있음.

print("3) word2vec 모델 학습 시작")
model=Word2Vec(sentences=docs, vector_size=200, window=4, min_count=2, sg=1)
print("3) word2vec 모델 학습 완료 ", time.time()-start)
print("-"*30)

print("4) 학습된 모델 저장 시작")
model.save("nvmx.model")
print("4) 학습된 모델 저장 완료", time.time()-start)
print("-"*30)

#학습된 말뭉치 개수
print("corpus_count(문장의 개수): ",model.corpus_count)
print("corpus_total_words(문장의 전체 단어 개수): ", model.corpus_total_words)



1) 말뭉치 데이터 읽기 시작!
리뷰 데이터 개수 200000
1) 말뭉치 데이터 읽기 완료:  0.9225001335144043
------------------------------
2) 형태소에서 명사만 추출 시작
2) 형태소에서 명사만 추출 완료  151.79968333244324
------------------------------
3) word2vec 모델 학습 시작
3) word2vec 모델 학습 완료  178.87816905975342
------------------------------
4) 학습된 모델 저장 시작
4) 학습된 모델 저장 완료 178.99107551574707
------------------------------
corpus_count(문장의 개수):  200000
corpus_total_words(문장의 전체 단어 개수):  1076896


### 학습된 Word2Vec모델 로드

학습된 모델을 이용하여 다양한 작업을 수행한다.

In [5]:
from gensim.models import Word2Vec

model= Word2Vec.load("nvmx.model")
print("corpus_total_words: ", model.corpus_total_words)
print("-"*30)

print("-"*30)
print("사랑: ",model.wv['사랑']) #위에서 저장한 벡터 크기(200)만큼 단어"사랑"을 분산 저장한 것.
#즉, 200차원의 벡터에 단어의 의미를 분산하여 저장한 것이다. => model.wv 모든 수치를 불러온다.
print("-"*30)


corpus_total_words:  1076896
------------------------------
------------------------------
사랑:  [-0.1001488  -0.6960788   0.33363962  0.20473452 -0.3637132   0.05606116
 -0.00858259 -0.03819323 -0.18480699  0.460605   -0.24563241 -0.06026712
  0.32489344 -0.01571137 -0.26641297  0.30298826 -0.05773379 -0.06535814
 -0.33301744 -0.31388193  0.6144688   0.27890465 -0.01699273  0.23428573
 -0.22755161 -0.4044268   0.30186167 -0.13488533 -0.01901794 -0.150223
  0.19412503  0.22348312  0.32626876 -0.20228553  0.19052085  0.36150476
 -0.1499315  -0.31790462 -0.24380583 -0.34183577 -0.12828264  0.217497
 -0.0351617  -0.23460808  0.56980044  0.43961716 -0.28077742 -0.04909912
  0.30041724  0.05927599 -0.05957438 -0.02391887  0.08908799  0.3482861
  0.04755105 -0.09948589 -0.29874706 -0.21374798 -0.10040756 -0.00250418
  0.13721345 -0.06176904 -0.43083987  0.03948259 -0.14863186 -0.04946771
 -0.3909251   0.18888159 -0.17819849  0.9785389   0.2123929  -0.16411856
  0.43369585  0.07734683  0.33676

In [7]:
#단어의 유사도 계산
print("일요일= 월요일\t", model.wv.similarity(w1='일요일', w2='월요일'))
print("-"*30)

print("안성기=배우\t", model.wv.similarity(w1='안성기', w2='배우'))
print("-"*30)

print("대기업=삼성\t", model.wv.similarity(w1="대기업", w2="배우"))
print("-"*30)

print("일요일!=삼성\t", model.wv.similarity(w1="일요일", w2="삼성")) #수치가 60%이면 유사성이 멀다고 생각하면 된다.
print("-"*30)

print("히어로!=삼성\t", model.wv.similarity(w1="히어로", w2="삼성"))
print("-"*30)

일요일= 월요일	 0.9218323
------------------------------
안성기=배우	 0.72570944
------------------------------
대기업=삼성	 0.36758643
------------------------------
일요일!=삼성	 0.6325083
------------------------------
히어로!=삼성	 0.47984147
------------------------------


In [11]:
#가장 유사한 단어 추출
print(model.wv.most_similar("안성기", topn=5)) #가장 유사한 단어 5개 추출
print("-"*200)

print(model.wv.most_similar("시리즈", topn=5))

[('공효진', 0.9420704245567322), ('한석규', 0.9416723847389221), ('지진희', 0.9410799741744995), ('박신양', 0.9392970204353333), ('엄정화', 0.9390084147453308)]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[('엑스맨', 0.8189730644226074), ('포터', 0.8081948757171631), ('해리', 0.7914246916770935), ('스타워즈', 0.7909550666809082), ('미이라', 0.7882712483406067)]
